// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnxuuoermmbrcexqpugg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZueHV1b2VybW1icmNleHFwdWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODMyMTQsImV4cCI6MjA3Mjk1OTIxNH0.WCx16ATIuVsvpdqVTPPisq3TRADMVsnSt6i7eA6qMw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});